/* NOTE - guard macros added by build script */

/*
 *  MT_Tracking.h
 *  MADTraC
 *
 *  Header for the MT_Tracking module of MADTraC.  This header should
 *  include any other headers you need and define the proper
 *  preprocessor definitions.
 *
 *  There are two versions of this file in the MADTraC project tree.
 *  If you have downloaded a packaged version of MT you may only have
 *  one version in the include directory.  If you have downloaded
 *  the source distribution or checked MT out from SVN there will be
 *  a version in the source tree as well.  That version is a prototype;
 *  the version in include is generated by adding content to the prototype.
 *  
 *  Created by Daniel Swain on 2/20/10.
 *
 */

#ifdef _MSC_VER
#pragma comment(lib, "FGCamera.lib")

#pragma comment(lib, "MT_Tracking.lib")
#endif
