/* NOTE - guard macros added by build script */

/*
 *  MT_Core.h
 *  MADTraC
 *
 *  Header for the MT_Core module of MADTraC.  This header should
 *  include any other headers you need and define the proper
 *  preprocessor definitions.
 *
 *  There are two versions of this file in the MADTraC project tree.
 *  If you have downloaded a packaged version of MT you may only have
 *  one version in the include directory.  If you have downloaded
 *  the source distribution or checked MT out from SVN there will be
 *  a version in the source tree as well.  That version is a prototype;
 *  the version in include is generated by adding content to the prototype.
 *  
 *  Created by Daniel Swain on 2/20/10.
 *
 */

#ifdef _MSC_VER
#pragma comment(lib, "highgui200.lib")
#pragma comment(lib, "cxcore200.lib")
#pragma comment(lib, "cv200.lib")
#pragma comment(lib, "wxmsw29ud_gl.lib")
#pragma comment(lib, "opengl32.lib")
#pragma comment(lib, "glu32.lib")
#pragma comment(lib, "wxmsw29ud_core.lib")
#pragma comment(lib, "wxbase29ud.lib")
#pragma comment(lib, "wxtiffd.lib")
#pragma comment(lib, "wxjpegd.lib")
#pragma comment(lib, "wxpngd.lib")
#pragma comment(lib, "wxzlibd.lib")
#pragma comment(lib, "wxexpatd.lib")
#pragma comment(lib, "kernel32.lib")
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "comdlg32.lib")
#pragma comment(lib, "winspool.lib")
#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "oleaut32.lib")
#pragma comment(lib, "uuid.lib")
#pragma comment(lib, "rpcrt4.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "wsock32.lib")
#pragma comment(lib, "wininet.lib")

#pragma comment(lib, "MT_Core.lib")
#endif /* _MSC_VER */
